
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 45
#define YY_END_OF_BUFFER 46
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[317] =
    {   0,
        0,    0,   46,   45,   44,   45,   27,   28,   39,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   27,    0,    0,    0,
        0,   28,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   29,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       10,    0,    0,   42,    0,    0,    0,    0,    0,    0,
        0,    0,   36,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,   43,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   40,    0,    0,   14,   14,    0,   14,    0,
        0,    0,    3,    3,   37,   37,   30,    0,    0,    0,
        0,    0,    0,    2,    2,    2,   11,   11,    0,    0,
        0,   41,    0,   15,   15,    0,   15,   24,    0,   14,
        0,    0,    0,    0,   24,    0,   12,    0,   12,    0,
       12,    0,    0,    0,    0,    4,    0,    0,    8,    2,
        2,    0,    0,   33,   33,   16,   16,    0,   16,   25,

        0,   15,    0,    0,    0,    0,   25,    0,    0,    0,
       13,   13,    0,   13,   22,   12,   17,    0,   17,   22,
        0,    0,    5,    0,    0,    9,    0,    0,    0,   26,
       16,    0,   21,    0,   26,    0,    0,    0,   19,   19,
       23,   13,    0,   18,    0,   23,    0,    0,    0,    0,
        0,   35,    0,   21,   20,   20,   18,    0,    1,    1,
        1,    6,    0,   38,    0,    0,    1,    1,    0,    0,
        0,    0,    0,    0,    0,    7,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   34,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,   31,    0,    0,    0,
        0,    0,    0,    0,   32,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,    5,    1,    1,    6,    7,    1,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   17,   18,   19,
       20,   21,   22,    1,   23,   24,   23,   25,   23,   26,
       23,   23,   27,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   28,   23,   23,   23,   23,   23,   23,   23,
       29,    1,   30,   31,   32,    1,   33,   34,   35,   36,

       37,   38,   39,   40,   41,   23,   23,   42,   43,   44,
       45,   46,   23,   47,   48,   49,   50,   51,   52,   23,
       53,   54,   55,   56,   57,   58,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[59] =
    {   0,
        1,    1,    2,    3,    4,    1,    1,    5,    6,    1,
        7,    8,    9,   10,   11,   12,   11,   13,   14,   15,
        3,    1,   16,   16,   16,   16,   16,   16,    1,    1,
        1,   17,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[370] =
    {   0,
        0,    0,  871, 1580, 1580,   39, 1580,   46, 1580,   60,
       61,   70,   79,   88,   89,   30,   58,   65,   63,   80,
       70,   87,   12,   77,   82,   45,  866,  848,    0,  108,
      123,  127,  858,    0,   18,  100,  101,  107,  106,  114,
      109,  131,  117,  122,  119,  130,  133,  142,  128,  152,
      147,  149,  158,  825,  837,  167,  838,  840,  830,  835,
      155,  160,  170,  169,  171,  140,  168,  178,  184,  126,
      189,  179,  176,  192,  186,  191,  199,  210,  205,  805,
     1580,  229,  823, 1580,  830,  213,  211,  202,  218,  212,
      231,  224,  226,  281,    0,  233,  254,  259,  242,  257,

      256,  272,  310,  278,  789,  268, 1580,  828,  817,  283,
      280,  331,  291,  299,  300,  347,  364,  824,  823,  311,
      270,  321,  337,  293,  343,  385,  346,  386,  338,  813,
      250,  809, 1580,  354,  401,  400,  351,  414,  428,  365,
      435,  410,  342,  442,  808, 1580,  816,  404,  415,  316,
      423,  429,  426,  451,  275,  477, 1580,  814,  427,  819,
      457, 1580,  478,  488,  475,  498,  512, 1580,  805,  513,
      529,  363,  530,  489,  810,  547,  546,  801,  502,  560,
      567,  771,  435,  533,  482,  413,  795,  524,  791,    0,
      550,    0,  762,  572,    0,  577,  570,  591,  598, 1580,

      793,  601,  617,  379,  618,  578,  798,  525,  789,  592,
      630,  619,  640,  639, 1580,  649,  788,  659,  625,  790,
      466,  625,  774,  567,  510,  773,  570,  782,  752, 1580,
      656,  675,  645,  772,  778,  671,  770,  672,  768,  676,
     1580,  688,  698,  681,  767,  769,  438,  697,  649,  302,
      677, 1580,  728,  759,  758,  703,  757,  446,  708,  510,
      717,  752,  609,  503,  753,  724,    0,  724,  695,  766,
      721,  578,  710,  723,  720, 1580,  717,  620,  711,  709,
      751,  714,    0,  559,  749,  732,  744,  719,  723,  722,
      721,  737,  723,  701,  702,  707,  700,  662,  637,  614,

      562,  527,  470,  451,  362,  371,  311,  227,  229,  163,
       99,   37,   22,    0,    0, 1580,  764,  780,  796,  812,
      665,  828,  844,  860,  876,  892,  908,  924,  940,  956,
      972,  988, 1004, 1020, 1036, 1052, 1068, 1084, 1100, 1116,
     1132, 1148, 1164, 1180, 1196, 1212, 1228, 1244, 1260,  730,
     1276, 1292, 1308, 1324, 1339, 1355, 1371, 1387, 1403, 1419,
     1435, 1451, 1467, 1483, 1499, 1515, 1531, 1547, 1562
    } ;

static const flex_int16_t yy_def[370] =
    {   0,
      316,    1,  316,  316,  316,  317,  316,  317,  316,  318,
      318,  318,  318,  318,  318,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,  316,  317,  319,  317,
      316,  317,  320,  321,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,  316,  319,  317,  316,  320,  316,  321,
       15,   15,   15,   15,   15,   15,   15,   15,   15,  317,
       15,   15,   15,   15,   15,   15,   15,   15,   15,  316,
      316,  317,  316,  316,  322,   15,   15,   15,   15,   15,
       15,   15,   15,  323,  324,   15,   15,   15,   15,   15,

       15,   15,  325,   15,  316,  317,  316,  322,  316,   15,
       15,  326,   15,   15,   15,  327,  323,  328,  324,   15,
       15,   15,   15,   15,   15,  329,  330,  325,   15,  316,
      317,  316,  316,   15,  331,  332,  333,  334,  326,   15,
      335,   15,  336,  327,  316,  316,  324,   15,   15,   15,
       15,   15,   15,  337,  338,  329,  316,  320,  317,  316,
      339,  316,  340,  341,  342,  343,  331,  316,  316,  333,
      334,  319,  319,  344,  320,  345,  346,  347,  348,  349,
      335,  350,   15,   15,   15,  317,  351,   15,  317,  352,
      338,  353,  316,  339,  354,  355,  356,  357,  340,  316,

      316,  342,  343,  319,  319,  358,  320,  316,  316,  319,
      359,  360,  361,  345,  316,  348,  316,  349,  319,  320,
      350,   15,  317,   15,  317,  351,   15,  353,  316,  316,
      356,  357,  319,  362,  320,  316,  316,  319,  316,  319,
      316,  360,  361,  319,  363,  320,  350,  364,   15,  317,
       15,  316,  316,  316,  316,  319,  316,  350,  365,  366,
      364,  317,  317,   15,  316,  316,  367,  366,  317,  316,
      316,  317,  316,  316,  317,  316,  316,  317,  316,  317,
      316,  317,  368,  317,  368,  317,  368,  317,  317,  317,
      317,  317,  316,  316,  316,  316,  316,  316,  316,  316,

      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  369,  369,    0,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316
    } ;

static const flex_int16_t yy_nxt[1639] =
    {   0,
        4,    5,    6,    7,    4,    7,    7,    7,    7,    7,
        7,    7,    7,    4,    7,    8,    7,    9,    7,    7,
        7,    7,   10,   11,   12,   13,   14,   15,    7,    7,
        7,   10,   10,   10,   16,   10,   17,   18,   10,   10,
       19,   10,   10,   20,   10,   21,   22,   23,   10,   24,
       25,   26,   10,   10,   27,    7,    7,    7,   29,   31,
       50,   32,   28,   28,   35,   29,   35,   33,   33,  314,
       35,   42,   28,   34,   34,   28,   28,   33,   35,   29,
       29,   28,   35,   34,   53,   28,   33,   30,  313,   29,
       28,   28,   34,   35,   28,   33,   33,   35,   29,   43,

       45,   34,   34,   28,   28,   36,   35,   29,   29,   44,
       35,   35,   46,   35,   37,   35,   47,   35,   35,   48,
       38,   70,   35,   49,   51,   35,   52,   29,   35,   35,
       35,   39,   35,   95,   35,   35,   31,   40,   57,   35,
       31,   41,   32,  312,   61,   29,   29,   56,   35,   35,
       62,   63,   35,   35,   64,   35,   66,   35,   35,   35,
       65,   35,   35,   67,   68,   35,   35,   35,   69,   35,
       35,   35,   71,   72,   35,   74,   75,   73,   35,   35,
       35,   35,   35,   35,   76,   35,   29,   77,   91,   78,
       35,   94,   35,   87,   35,   35,   86,   35,   79,   35,

       35,   35,   88,   35,   35,   89,   35,   35,   35,  311,
       35,   90,   35,   82,   93,   92,   35,   35,   35,   35,
       35,   35,   35,   35,   98,   96,   35,   35,   35,   97,
       35,   35,   35,   99,   35,  100,   35,   35,   35,  101,
       35,   35,  102,   35,   35,  103,  104,   35,   29,  110,
      112,   35,  111,   35,   35,  114,  113,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,  115,  310,   29,
       35,  116,   35,  106,   35,  309,   35,  190,   35,   35,
      120,   35,  123,   35,  118,   35,  121,   29,  190,   59,
       35,  118,   58,  118,   35,  122,  125,  161,  118,  118,

      118,  118,   35,  124,   35,   35,   35,   35,   35,   35,
      126,   35,  127,  308,  129,  134,  135,   33,  149,  131,
       35,   29,   35,   34,   35,  127,   35,  140,   35,   29,
       35,   35,   35,  136,  263,   35,  152,  141,   33,   35,
      159,   35,  142,   35,   34,   35,  137,   35,   35,  143,
      138,   35,   35,  157,   33,  150,  148,   28,  168,   35,
       34,   29,   28,   35,  185,   29,   29,  118,   35,   35,
       29,  151,  145,   35,  118,   58,  118,  153,  173,  307,
       81,  118,  118,  118,  118,   35,   35,  154,  127,   35,
       35,   35,   33,  158,  205,   35,   81,  163,  155,   34,

       28,  127,   35,  164,   29,   29,   35,  168,   33,  306,
      169,  176,  169,   35,   34,  170,  165,   35,   55,  138,
      166,   55,   55,  182,  172,  186,  169,   55,  189,  173,
      136,  187,   29,  174,  192,  175,  183,  177,  169,  178,
      169,   34,   33,  170,  143,   85,   29,  138,   34,   33,
      179,  184,   35,   85,  180,   34,   35,   28,   35,  266,
      225,   29,   35,   35,  190,  188,   28,   35,  195,  222,
       29,   35,   28,   85,   35,   35,   29,   35,   35,  154,
      196,   35,  200,   35,   33,   33,  258,   35,   28,  305,
      155,   34,   28,  197,   29,  200,   29,  198,  201,  169,

      201,  169,   55,  202,  208,   55,   55,  166,  204,  215,
      201,   55,  267,  205,  164,  247,  304,  206,  224,  207,
      168,   29,  201,  267,  201,   34,  209,  202,  170,   29,
       35,  166,   29,   55,   35,  223,   55,   55,  209,  172,
      208,  169,   55,  210,  173,  173,   81,   81,  174,  211,
      178,   35,  190,  215,   33,   35,  227,   85,  250,  303,
       34,  216,  212,  190,  302,  180,  213,   55,   55,  177,
       55,  178,   35,   55,  220,  219,   35,  230,   29,  178,
       34,   35,  216,  195,  230,   35,  180,   28,  201,   29,
      201,   29,  231,  236,  286,   55,  198,   29,   55,   55,

      196,   55,  249,   28,   55,  235,  233,  240,  200,   81,
      234,   34,  275,  231,  237,   35,  202,  198,   35,   35,
       29,   55,   35,  251,   55,   55,  241,  204,   29,  201,
       55,  238,  205,  205,   81,   81,  206,  241,   29,   29,
      219,  211,   81,  301,   55,  242,  246,   55,   55,  213,
       55,  262,   34,   55,  242,  244,  215,  269,  213,  245,
      233,  248,   81,  230,  216,  300,   55,   55,   29,   55,
      280,  231,   55,   35,  219,   29,   81,   35,  178,   55,
       60,   60,   55,   55,  237,   55,  236,  256,   55,   81,
      233,  240,   81,   81,  234,  241,  244,   35,   81,  259,

      299,   35,   55,  242,   33,   55,   55,   29,   55,  264,
      260,   55,   28,  244,   29,   81,   29,  245,  256,  259,
       81,  267,  278,   28,   33,   35,  267,   29,   29,   35,
      260,   85,   28,   29,  288,  272,   29,  267,   29,   29,
       29,   29,   29,  298,  293,   60,   60,  297,  296,  295,
      294,   29,  287,  282,  284,  290,   29,  287,  283,  281,
      279,  289,  291,  277,  292,   28,  276,  274,  273,  271,
      270,   29,  257,  255,  254,   28,  265,   59,   28,   28,
       28,   35,  257,  239,   35,  255,   59,  254,  253,   35,
      252,   35,   29,   29,   35,   35,   35,   55,   59,   55,

       55,   55,   55,  217,  239,   55,   59,   55,  236,  229,
       29,   55,   55,   58,   29,  221,  217,   58,   59,   58,
      208,  193,   59,   58,  147,  107,  162,   58,   58,  108,
      160,  147,  146,  108,  133,  108,  132,  130,  109,  108,
      107,  105,   85,  108,  108,  117,  117,   84,   83,  117,
      117,  117,  117,   57,   81,  117,  117,  117,  117,  117,
      117,  119,  119,   80,  119,  119,   59,   29,   54,  119,
      316,  316,  316,  119,  119,  119,  119,  128,  316,  316,
      128,  316,  316,  316,  316,  128,  316,  128,  316,  316,
      128,  128,  128,  139,  316,  316,  139,  316,  316,  316,

      316,  139,  316,  139,  316,  316,  139,  139,  139,  144,
      316,  316,  144,  316,  316,  316,  316,  144,  316,  144,
      316,  316,  144,  144,  144,  118,  118,  316,  316,  118,
      118,  316,  118,  316,  316,  118,  118,  118,  118,  118,
      118,  156,  316,  316,  156,  316,  316,  316,  316,  156,
      316,  156,  316,  316,  156,  156,  156,  127,  316,  316,
      127,  316,  316,  316,  316,  316,  316,  127,  316,  316,
      127,  127,  127,  167,  316,  316,  167,  316,  316,  316,
      316,  167,  316,  167,  316,  316,  167,  167,  167,  136,
      316,  316,  136,  316,  136,  316,  136,  316,  316,  136,

      316,  316,  136,  136,  136,  137,  316,  316,  137,  316,
      316,  316,  316,  316,  316,  137,  316,  316,  137,  137,
      137,  171,  316,  171,  171,  171,  171,  316,  171,  171,
      316,  171,  316,  316,  171,  171,  171,  181,  316,  181,
      181,  316,  316,  316,  316,  181,  316,  181,  316,  316,
      181,  181,  181,  143,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  143,  316,  316,  143,  143,  143,  154,
      316,  316,  316,  316,  316,  316,  316,  154,  316,  154,
      316,  316,  154,  154,  154,  191,  316,  316,  316,  316,
      316,  316,  316,  191,  316,  316,  316,  316,  316,  191,

      191,  194,  316,  316,  316,  316,  316,  194,  316,  316,
      316,  194,  316,  316,  194,  194,  194,  199,  316,  316,
      199,  316,  316,  316,  316,  199,  316,  199,  316,  316,
      199,  199,  199,  164,  316,  316,  164,  316,  164,  316,
      164,  316,  316,  164,  316,  316,  164,  164,  164,  165,
      316,  316,  165,  316,  316,  316,  316,  316,  316,  165,
      316,  316,  165,  165,  165,  203,  316,  203,  203,  203,
      203,  316,  203,  203,  316,  203,  316,  316,  203,  203,
      203,  174,  316,  316,  316,  316,  174,  316,  174,  316,
      316,  174,  316,  316,  174,  174,  174,  214,  316,  316,

      214,  316,  316,  316,  316,  214,  316,  214,  316,  316,
      214,  214,  214,  177,  316,  177,  177,  316,  316,  316,
      316,  316,  316,  177,  316,  316,  177,  177,  177,  178,
      316,  178,  316,  316,  316,  316,  316,  316,  316,  178,
      316,  316,  178,  178,  178,  179,  316,  316,  179,  316,
      316,  316,  316,  316,  316,  179,  316,  316,  179,  179,
      179,  218,  316,  218,  218,  218,  218,  316,  316,  218,
      316,  218,  316,  316,  218,  218,  218,  226,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  226,  316,  316,
      226,  226,  226,  190,  316,  316,  316,  316,  316,  316,

      316,  190,  316,  316,  316,  316,  316,  190,  190,  228,
      228,  316,  316,  316,  316,  316,  316,  228,  316,  228,
      316,  228,  228,  228,  228,  195,  316,  316,  316,  316,
      316,  195,  316,  316,  316,  316,  316,  316,  316,  195,
      196,  316,  316,  196,  316,  316,  316,  316,  316,  316,
      196,  316,  316,  196,  196,  196,  197,  316,  316,  197,
      316,  316,  316,  316,  316,  316,  197,  316,  316,  197,
      197,  197,  232,  316,  232,  232,  232,  232,  316,  316,
      232,  316,  232,  316,  316,  232,  232,  232,  206,  316,
      316,  316,  316,  206,  316,  206,  316,  316,  206,  316,

      316,  206,  206,  206,  211,  316,  316,  211,  316,  316,
      316,  316,  316,  316,  211,  316,  316,  211,  211,  211,
      212,  316,  316,  212,  316,  316,  316,  316,  316,  316,
      212,  316,  316,  212,  212,  212,  243,  316,  243,  243,
      243,  243,  316,  316,  243,  316,  243,  316,  316,  243,
      243,  243,  234,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  234,  316,  316,  234,  234,  234,  245,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  245,  316,
      316,  245,  245,  245,  261,  316,  316,  261,  316,  316,
      316,  316,  261,  316,  261,  316,  316,  261,  261,  261,

      259,  316,  316,  316,  316,  316,  316,  316,  259,  316,
      259,  316,  316,  259,  259,  259,  268,  316,  316,  316,
      316,  316,  316,  316,  268,  316,  316,  316,  316,  316,
      268,  268,  267,  316,  316,  316,  316,  316,  316,  316,
      267,  316,  316,  316,  316,  316,  267,  267,  285,  316,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  315,  316,  316,  316,  316,  316,  315,
      316,  316,  316,  316,  316,  316,  316,  315,  315,    3,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,

      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316
    } ;

static const flex_int16_t yy_chk[1639] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    6,    8,
       23,    8,   10,   11,   23,    8,   35,   10,   11,  313,
       35,   16,   12,   10,   11,   10,   11,   12,   16,   10,
       11,   13,   16,   12,   26,   12,   13,    6,  312,   12,
       14,   15,   13,   26,   13,   14,   15,   26,   13,   17,

       19,   14,   15,   14,   15,   11,   17,   14,   15,   18,
       17,   19,   20,   18,   12,   19,   21,   18,   21,   21,
       13,   45,   21,   22,   24,   24,   25,   30,   20,   24,
       25,   14,   20,   70,   25,   22,   31,   15,   31,   22,
       32,   15,   32,  311,   36,   70,   32,   30,   36,   37,
       37,   38,   36,   37,   39,   38,   41,   41,   39,   38,
       40,   41,   40,   42,   43,   43,   40,   45,   44,   43,
       44,   45,   46,   47,   44,   48,   49,   47,   46,   42,
       49,   47,   46,   42,   50,   47,   56,   51,   66,   52,
       48,   69,   66,   62,   48,   51,   61,   52,   53,   51,

       50,   52,   63,   61,   50,   64,   53,   61,   62,  310,
       53,   65,   62,   56,   68,   67,   67,   64,   63,   65,
       67,   64,   63,   65,   73,   71,   68,   72,   73,   72,
       68,   72,   69,   74,   75,   75,   69,   71,   75,   76,
       74,   71,   77,   76,   74,   78,   79,   77,   82,   86,
       88,   77,   87,   79,   88,   90,   89,   79,   78,   87,
       90,   86,   78,   87,   90,   86,   89,   91,  309,  131,
       89,   92,   92,   82,   93,  308,   92,  155,   93,   91,
       96,   96,   99,   91,   94,   96,   97,  106,  155,   94,
       99,   94,   94,   94,   99,   98,  101,  131,   94,   94,

       94,   94,   97,  100,  101,  100,   97,   98,  101,  100,
      102,   98,  103,  307,  104,  110,  111,  103,  121,  106,
      102,  250,  121,  103,  102,  103,  104,  113,  111,  103,
      104,  110,  111,  112,  250,  110,  124,  114,  112,  113,
      129,  124,  115,  113,  112,  124,  112,  114,  115,  116,
      112,  114,  115,  127,  116,  122,  120,  143,  137,  120,
      116,  143,  116,  120,  150,  127,  116,  117,  150,  122,
      137,  123,  117,  122,  117,  117,  117,  125,  172,  306,
      172,  117,  117,  117,  117,  123,  129,  126,  128,  123,
      129,  125,  126,  128,  204,  125,  204,  134,  126,  128,

      126,  128,  134,  135,  126,  128,  134,  136,  135,  305,
      136,  140,  136,  140,  135,  136,  135,  140,  138,  136,
      135,  138,  138,  142,  138,  151,  138,  138,  153,  138,
      139,  152,  186,  138,  159,  139,  148,  141,  139,  141,
      139,  139,  141,  139,  144,  247,  159,  139,  141,  144,
      141,  149,  148,  258,  141,  144,  148,  144,  142,  258,
      186,  144,  142,  149,  154,  152,  154,  149,  161,  183,
      154,  151,  161,  221,  153,  151,  161,  152,  153,  156,
      163,  152,  165,  183,  156,  163,  247,  183,  161,  304,
      156,  163,  156,  163,  165,  164,  156,  163,  164,  174,

      164,  174,  166,  164,  174,  166,  166,  164,  166,  179,
      166,  166,  260,  166,  167,  221,  303,  166,  185,  167,
      170,  179,  167,  260,  167,  167,  170,  167,  170,  225,
      185,  167,  170,  171,  185,  184,  171,  171,  208,  171,
      208,  171,  171,  173,  171,  173,  171,  173,  171,  176,
      177,  264,  191,  177,  176,  264,  188,  191,  225,  302,
      176,  177,  176,  191,  301,  177,  176,  180,  180,  181,
      180,  181,  188,  180,  181,  180,  188,  197,  284,  180,
      181,  184,  181,  194,  196,  184,  181,  194,  206,  197,
      206,  194,  196,  206,  284,  198,  196,  272,  198,  198,

      199,  198,  224,  194,  198,  199,  198,  210,  202,  210,
      198,  199,  272,  199,  202,  224,  202,  199,  227,  224,
      202,  203,  227,  227,  203,  203,  212,  203,  263,  203,
      203,  205,  203,  205,  203,  205,  203,  211,  212,  278,
      219,  214,  219,  300,  213,  211,  214,  213,  213,  211,
      213,  249,  214,  213,  214,  213,  216,  263,  214,  213,
      233,  222,  233,  231,  216,  299,  218,  218,  216,  218,
      278,  231,  218,  222,  218,  231,  218,  222,  218,  232,
      321,  321,  232,  232,  236,  232,  236,  238,  232,  238,
      232,  240,  232,  240,  232,  242,  244,  249,  244,  248,

      298,  249,  243,  242,  248,  243,  243,  242,  243,  251,
      248,  243,  248,  243,  269,  243,  248,  243,  256,  261,
      256,  259,  275,  259,  261,  251,  268,  259,  280,  251,
      261,  268,  261,  282,  286,  269,  261,  268,  288,  275,
      291,  290,  289,  297,  292,  350,  350,  296,  295,  294,
      293,  286,  287,  280,  282,  289,  292,  285,  281,  279,
      277,  288,  290,  274,  291,  317,  273,  271,  270,  266,
      265,  262,  257,  255,  254,  317,  253,  246,  317,  317,
      317,  318,  245,  239,  318,  237,  235,  234,  229,  318,
      228,  318,  226,  223,  318,  318,  318,  319,  220,  319,

      319,  319,  319,  217,  209,  319,  207,  319,  201,  193,
      189,  319,  319,  320,  187,  182,  178,  320,  175,  320,
      169,  160,  158,  320,  147,  145,  132,  320,  320,  322,
      130,  119,  118,  322,  109,  322,  108,  105,   85,  322,
       83,   80,   60,  322,  322,  323,  323,   59,   58,  323,
      323,  323,  323,   57,   55,  323,  323,  323,  323,  323,
      323,  324,  324,   54,  324,  324,   33,   28,   27,  324,
        3,    0,    0,  324,  324,  324,  324,  325,    0,    0,
      325,    0,    0,    0,    0,  325,    0,  325,    0,    0,
      325,  325,  325,  326,    0,    0,  326,    0,    0,    0,

        0,  326,    0,  326,    0,    0,  326,  326,  326,  327,
        0,    0,  327,    0,    0,    0,    0,  327,    0,  327,
        0,    0,  327,  327,  327,  328,  328,    0,    0,  328,
      328,    0,  328,    0,    0,  328,  328,  328,  328,  328,
      328,  329,    0,    0,  329,    0,    0,    0,    0,  329,
        0,  329,    0,    0,  329,  329,  329,  330,    0,    0,
      330,    0,    0,    0,    0,    0,    0,  330,    0,    0,
      330,  330,  330,  331,    0,    0,  331,    0,    0,    0,
        0,  331,    0,  331,    0,    0,  331,  331,  331,  332,
        0,    0,  332,    0,  332,    0,  332,    0,    0,  332,

        0,    0,  332,  332,  332,  333,    0,    0,  333,    0,
        0,    0,    0,    0,    0,  333,    0,    0,  333,  333,
      333,  334,    0,  334,  334,  334,  334,    0,  334,  334,
        0,  334,    0,    0,  334,  334,  334,  335,    0,  335,
      335,    0,    0,    0,    0,  335,    0,  335,    0,    0,
      335,  335,  335,  336,    0,    0,    0,    0,    0,    0,
        0,    0,    0,  336,    0,    0,  336,  336,  336,  337,
        0,    0,    0,    0,    0,    0,    0,  337,    0,  337,
        0,    0,  337,  337,  337,  338,    0,    0,    0,    0,
        0,    0,    0,  338,    0,    0,    0,    0,    0,  338,

      338,  339,    0,    0,    0,    0,    0,  339,    0,    0,
        0,  339,    0,    0,  339,  339,  339,  340,    0,    0,
      340,    0,    0,    0,    0,  340,    0,  340,    0,    0,
      340,  340,  340,  341,    0,    0,  341,    0,  341,    0,
      341,    0,    0,  341,    0,    0,  341,  341,  341,  342,
        0,    0,  342,    0,    0,    0,    0,    0,    0,  342,
        0,    0,  342,  342,  342,  343,    0,  343,  343,  343,
      343,    0,  343,  343,    0,  343,    0,    0,  343,  343,
      343,  344,    0,    0,    0,    0,  344,    0,  344,    0,
        0,  344,    0,    0,  344,  344,  344,  345,    0,    0,

      345,    0,    0,    0,    0,  345,    0,  345,    0,    0,
      345,  345,  345,  346,    0,  346,  346,    0,    0,    0,
        0,    0,    0,  346,    0,    0,  346,  346,  346,  347,
        0,  347,    0,    0,    0,    0,    0,    0,    0,  347,
        0,    0,  347,  347,  347,  348,    0,    0,  348,    0,
        0,    0,    0,    0,    0,  348,    0,    0,  348,  348,
      348,  349,    0,  349,  349,  349,  349,    0,    0,  349,
        0,  349,    0,    0,  349,  349,  349,  351,    0,    0,
        0,    0,    0,    0,    0,    0,    0,  351,    0,    0,
      351,  351,  351,  352,    0,    0,    0,    0,    0,    0,

        0,  352,    0,    0,    0,    0,    0,  352,  352,  353,
      353,    0,    0,    0,    0,    0,    0,  353,    0,  353,
        0,  353,  353,  353,  353,  354,    0,    0,    0,    0,
        0,  354,    0,    0,    0,    0,    0,    0,    0,  354,
      355,    0,    0,  355,    0,    0,    0,    0,    0,    0,
      355,    0,    0,  355,  355,  355,  356,    0,    0,  356,
        0,    0,    0,    0,    0,    0,  356,    0,    0,  356,
      356,  356,  357,    0,  357,  357,  357,  357,    0,    0,
      357,    0,  357,    0,    0,  357,  357,  357,  358,    0,
        0,    0,    0,  358,    0,  358,    0,    0,  358,    0,

        0,  358,  358,  358,  359,    0,    0,  359,    0,    0,
        0,    0,    0,    0,  359,    0,    0,  359,  359,  359,
      360,    0,    0,  360,    0,    0,    0,    0,    0,    0,
      360,    0,    0,  360,  360,  360,  361,    0,  361,  361,
      361,  361,    0,    0,  361,    0,  361,    0,    0,  361,
      361,  361,  362,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  362,    0,    0,  362,  362,  362,  363,    0,
        0,    0,    0,    0,    0,    0,    0,    0,  363,    0,
        0,  363,  363,  363,  364,    0,    0,  364,    0,    0,
        0,    0,  364,    0,  364,    0,    0,  364,  364,  364,

      365,    0,    0,    0,    0,    0,    0,    0,  365,    0,
      365,    0,    0,  365,  365,  365,  366,    0,    0,    0,
        0,    0,    0,    0,  366,    0,    0,    0,    0,    0,
      366,  366,  367,    0,    0,    0,    0,    0,    0,    0,
      367,    0,    0,    0,    0,    0,  367,  367,  368,    0,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  369,    0,    0,    0,    0,    0,  369,
        0,    0,    0,    0,    0,    0,    0,  369,  369,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,

      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[46] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 1, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "cparser.l"
#line 4 "cparser.l"
	#include <stdio.h>
	#include "y.tab.h"
	#include <math.h>
    char className[100];
#line 950 "lex.yy.c"
/*Declararea regex-urilor pentru detectarea diferitelor pattern-uri caracteristice (antetul unei clase, o structura repetitiva, o asignare, o instanta a unui obiect, etc.)*/
#line 952 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 51 "cparser.l"



#line 1173 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 317 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1580 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 54 "cparser.l"
{ /*Token-ul returnat in cazul in care se face match pe regex-ul pentru declararea pachetului*/
            return NAMESPACE;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 57 "cparser.l"
{	/*Returnarea token-ului pentru liniile de cod in care se face match cu regex-ul de importare a unor biblioteci*/
            printf("%s\n", yytext);
			return USING;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 61 "cparser.l"
{	/*Returnarea token-ului pentru liniile in care se face match cu regex-ul de declarare a antetului unei clase*/
            /*Se printeaza toata linia, mai putin "{", care va fi inlocuita de ":", caracteristica specifica sintaxei Python*/
            int contor = 0;
            while (contor < strlen(yytext) - 1) {
                  printf("%c", yytext[contor]);
                  contor++;
              }
            printf(":\n");

			strcpy(className, yytext + 6);
			return CLASA; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 75 "cparser.l"
{
                /*Cand intalneste modificatorii de acces ii ignora si verifica ce este in continuare*/
            }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 78 "cparser.l"
{}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 79 "cparser.l"
{}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 82 "cparser.l"
{ return GETSET;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 84 "cparser.l"
{ /*Cand intalneste proprietatea de "static" a unui field sau a unei metode o ignora si continua*/ }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 86 "cparser.l"
{ /*Cand se face match cu regex-ul pentru "return" in cadrul unei metode se va transmite token-ul corespunzator si se va printa linia de cod care returneaza rezultatul metodei respective*/
			int contor = 0;
			while(contor < strlen(yytext)){
				printf("%c", yytext[contor]);
				contor++;
			}
			return RETURNT;
		}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 94 "cparser.l"
{ 	/*Cand se face match cu regex-ul de instanta a unui obiect se va afisa in fisierul de iesire doar numele noului obiect creat si numle clasei urmat de doua paranteze si se returneaza token-ul corespunzator*/
                int rez = checkTwoWords(yytext);
              if (rez == 1) {
                int contor = 0;
                while (yytext[contor] == ' ')
                  printf("%c", yytext[contor++]);
                while (yytext[contor] != ' ')
                  contor++;
                contor++;
                while(yytext[contor] != '=') 
                  printf("%c", yytext[contor++]);
                
                printf("= ");
                contor += 2;

                if (yytext[contor] == 'n' && yytext[contor + 1] == 'e' && yytext[contor + 2] == 'w')
                  contor += 4;

                while (contor < strlen(yytext) - 1)
                  printf("%c", yytext[contor++]);
              } else {
				  	int contor = 0;
					while(contor < strlen(yytext) - 1){
						printf("%c", yytext[contor]);
						contor++;
					}
			  }
			  return ASIG;
			}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 124 "cparser.l"
{  /*Verifica daca este o metoda definita ca si void */
            int contor = 5;
			printf("def ");	
            while (contor < strlen(yytext)) {
                  printf("%c", yytext[contor]);
                  contor++;
              }
			return TIP_PRIMITIV;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 132 "cparser.l"
{  /*Verifica daca este o variabila definita ca si String */
            int contor = 7;
            while (contor < strlen(yytext)) {
                  printf("%c", yytext[contor]);
                  contor++;
              }
            printf(": str");
			return TIP_PRIMITIV;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 140 "cparser.l"
{ /*Verifica daca este o variabila definita ca si Integer */
            int contor = 8;
            while (contor < strlen(yytext)) {
                  printf("%c", yytext[contor]);
                  contor++;
              }
            printf(": int");
			return TIP_PRIMITIV;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 148 "cparser.l"
{   /*Verifica daca este o variabila definita ca si Float */
            int contor = 6;
            while (contor < strlen(yytext)) {
                  printf("%c", yytext[contor]);
                  contor++;
              }
            printf(": float");
			return TIP_PRIMITIV;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 156 "cparser.l"
{  /*Verifica daca este o variabila definita ca si Double */
            int contor = 7;
            while (contor < strlen(yytext)) {
                  printf("%c", yytext[contor]);
                  contor++;
              }
            printf(": float");
			return TIP_PRIMITIV;}		
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 164 "cparser.l"
{ 
            /*Verifica daca este o variabila definita ca si Boolean */
            int contor = 8;
            while (contor < strlen(yytext)) {
                  printf("%c", yytext[contor]);
                  contor++;
              }
            printf(": bool");
			return TIP_PRIMITIV;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 174 "cparser.l"
{ /*Verifica daca este o variabila definita ca si String care este initializata la o valoare*/
            int contor = 7;
            while (contor < strlen(yytext)) {
                  printf("%c", yytext[contor]);
                  contor++;
              }
			return TIP_PRIMITIV;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 181 "cparser.l"
{/*Verifica daca este o variabila definita ca si Integer care este initializata la o valoare*/ 
            int contor = 8;
            while (contor < strlen(yytext)) {
                  printf("%c", yytext[contor]);
                  contor++;
              }
			return TIP_PRIMITIV;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 188 "cparser.l"
{  /*Verifica daca este o variabila definita ca si Float care este initializata la o valoare*/ 
            int contor = 6;
            while (contor < strlen(yytext)) {
                  printf("%c", yytext[contor]);
                  contor++;
              }
			return TIP_PRIMITIV;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 195 "cparser.l"
{ /*Verifica daca este o variabila definita ca si Double care este initializata la o valoare*/ 
            int contor = 7;
            while (contor < strlen(yytext)) {
                  printf("%c", yytext[contor]);
                  contor++;
              }
			return TIP_PRIMITIV;}		
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 202 "cparser.l"
{/*Verifica daca este o variabila definita ca si Boolean care este initializata la o valoare*/ 
            int contor = 8;
            while (contor < strlen(yytext)) {
                  printf("%c", yytext[contor]);
                  contor++;
              }
			return TIP_PRIMITIV;}			
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 210 "cparser.l"
{/*Verifica daca este o metoda care va intoarce un String */ 
            int contor = 7;
			printf("def ");
            while (contor < strlen(yytext)) {
                  printf("%c", yytext[contor]);
                  contor++;
              }
			
			return TIP_PRIMITIV;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 219 "cparser.l"
{/*Verifica daca este o metoda care va intoarce un Integer */  
            int contor = 8;
			printf("def ");
            while (contor < strlen(yytext)) {
                  printf("%c", yytext[contor]);
                  contor++;
              }
			return TIP_PRIMITIV;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 227 "cparser.l"
{ /*Verifica daca este o metoda care va intoarce un Float */   
            int contor = 6;
			printf("def ");
            while (contor < strlen(yytext)) {
                  printf("%c", yytext[contor]);
                  contor++;
              }
			return TIP_PRIMITIV;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 235 "cparser.l"
{/*Verifica daca este o metoda care va intoarce un Double */   
            int contor = 7;
			printf("def ");
            while (contor < strlen(yytext)) {
                  printf("%c", yytext[contor]);
                  contor++;
              }
			return TIP_PRIMITIV;}		
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 243 "cparser.l"
{/*Verifica daca este o metoda care va intoarce un Boolean */  
            int contor = 8;
			printf("def ");
            while (contor < strlen(yytext)) {
                  printf("%c", yytext[contor]);
                  contor++;
              }
			return TIP_PRIMITIV;}	
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 252 "cparser.l"
{return yytext[0];}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 254 "cparser.l"
{	/*Cand se face match pe un numar natural, valoarea acestuia este scrisa in fisierul de iesire asa cum este intalnita si in fisierul de intrare si se returneaza si un token corespunzator*/
            printf("%s", yytext);
			return VALOARE;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 258 "cparser.l"
{/*Cand se face match pe un numar flotant, valoarea acestuia este scrisa in fisierul de iesire asa cum este intalnita si in fisierul de intrare si se returneaza si un token corespunzator*/
                    return VALOARE_FLOTANTA;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 261 "cparser.l"
{/*Cand se face match cu regex-ul pentru inceperea structurii alternative if-else se scrie in fisierul de iesire conditia si se returneaza token-ul corespunztor*/	
        printf("%s:", yytext);
		return DACA;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 265 "cparser.l"
{/*Cand se face match cu regex-ul pentru definirea metodei principale a programului(main), se va returna token-ul corespunzator*/
            return FUNCTIE_PRINCIPALA;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 268 "cparser.l"
{  /*Vefica daca este metoda main si face throw la o exceptie sau mai multe*/
                return FUNCTIE_PRINCIPALA;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 272 "cparser.l"
{  /*Verfica daca se face throw unei exceptii in signaura metodei apelate*/
            return EXCEPTIE;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 276 "cparser.l"
{ /*Cand se face match cu regex-ul de printare corespunzatror modului de apelare a metodei corespunzatoare din limbajul java, se va scrie in fisierul de iesire numele metodei corespunzatoare din Python (print)
  urmat de aceeasi parametrii pe care ii primeste si metoda din limbajul Java*/
            printf("print(");
		  int contor = 17;
			while(contor < strlen(yytext)) {
				printf("%c", yytext[contor]);
                contor++;
			}
			return AFISARE;
		}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 287 "cparser.l"
{	/*Verifica daca este o instructiune de tip while*/
            int contor = 0;
			while ( yytext[contor] != '(') {
				printf("%c", yytext[contor]);
				contor++;
			}
			contor++;
			while ( yytext[contor] != ')') {
				printf("%c", yytext[contor]);
				contor++;
			}
			contor++;
			return CAT_TIMP;
		}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 305 "cparser.l"
{ /*Verifica daca am ajuns pe ramura de else*/ 
         printf("%s:", yytext);
		 return ALTFEL;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 309 "cparser.l"
{ /*Verifica daca este o intructiune for*/
		printf("for ");
		int contor = 4;
		while (yytext[contor] != ' ') {
			printf("%c", yytext[contor]);
            contor++;
		}
		contor+=3;
		printf(" in range(");
		while (yytext[contor + 1] != ' ') {
			printf("%c", yytext[contor]);
            contor++;
		}
		printf(", ");
 		contor++;
		while (yytext[contor] != '<' && yytext[contor] != '>') {
            contor++;
		}
		contor++;
		if (yytext[contor] == '=')
			contor++;
		contor++;
		while (yytext[contor + 1] != ' ') {
			printf("%c", yytext[contor]);
            contor++;
		}
		printf(")");
		return PENTRU;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 338 "cparser.l"
{return RETURNEAZA;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 339 "cparser.l"
{return EOL;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 343 "cparser.l"
{  /*Verifica daca se invoca o metoda fara parametrii de catre o instanta*/
			int contor = 0;
            while (contor < strlen(yytext) - 1) {
                  printf("%c", yytext[contor]);
                  contor++;
              }
			
			return FUNCTIE;		
		}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 353 "cparser.l"
{ /*Verifica daca se invoca o metoda cu parametrii de catre o instanta*/
			int contor = 0;
            while (contor < strlen(yytext) - 1) {
                  printf("%c", yytext[contor]);
                  contor++;
              }
			return FUNCTIE;
		}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 362 "cparser.l"
{ /*Verifica daca se invoca o metoda statica fara parametrii*/
			int contor = 0;
            while (contor < strlen(yytext) - 1) {
                  printf("%c", yytext[contor]);
                  contor++;
              }
			return FUNCTIE;		
		}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 371 "cparser.l"
{ /*Verifica daca se invoca o metoda statica cu parametrii*/
			int contor = 0;
            while (contor < strlen(yytext) - 1) {
                  printf("%c", yytext[contor]);
                  contor++;
              }
			return FUNCTIE;
		}
	YY_BREAK
case 44:
/* rule 44 can match eol */
YY_RULE_SETUP
#line 380 "cparser.l"
{}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 382 "cparser.l"
ECHO;
	YY_BREAK
#line 1713 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 317 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 317 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 316);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 382 "cparser.l"

/*Aceasta functie verifica daca exista doua cuvinte inainte si dupa egal*/
int checkTwoWords(char *s){
    int contor = 0;
    int word = 0;
    while (s[contor] == ' ')
      contor++;
    while (s[contor] != '=') {
        while (s[contor] != ' ' && s[contor] != '=') {
            contor++;
        }
        word++;
        contor++;
    }
    if (word == 2)
        return 1;
    else
        return 0;
}
